name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm i --frozen-lockfile
      - name: Type Check
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint:ci
      - name: Unit Tests
        run: pnpm test:ci
      - name: Secret Scan (gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enforce PR Body (Codex mention/sections)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          body=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          echo "$body" | grep -qi "@codex" || (echo "PR本文に @codex を含めてください"; exit 1)
          echo "$body" | grep -qi "レビュー方針" || (echo "PR本文に レビュー方針 セクションを追加してください"; exit 1)
